version: '3.8'
services:
  redis-cluster:
    image: alvinhub/redis-cluster:6.2.6
    environment:
     IP: ${REDIS_CLUSTER_IP}
     SENTINEL: ${REDIS_USE_SENTINEL}
     STANDALONE: ${REDIS_USE_STANDALONE}
    build:
      context: .
      args:
        redis_version: '6.2.6'
    hostname: redis-cluster
    ports:
      - '7000-7050'
      - '5000-5010'
